version: '3.8'

services:
  postgres-test:
    image: postgres:12.4-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: symfony_test
      POSTGRES_USER: symfony_test
      POSTGRES_PASSWORD: super_password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"

  php-test:
    build:
      context: .
      target: app_php
    image: zv-docker/php:dev
    restart: on-failure
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - "postgres-test"
    volumes:
      - .:/app:rw,cached
      - var:/app/var
    ports:
      - "9005:9000"

  nginx-test:
    build:
      context: .
      target: app_nginx
    image: zv-docker/nginx:dev
    restart: on-failure
    depends_on:
      - "php-test"
    volumes:
      - ./public:/app/public:ro
    ports:
      - "8085:80"

volumes:
  db-data:
  var:
